### ISSUE TITLE
Integrating into existing java app

### ISSUE THREAD

**Issue by ugintl** [ShaMan123/react-native-sketch-canvas#10]
Can I integrate it into existing java app?

**Comment by ShaMan123** [comment]
I have built this in mind for java only integration, but to accomplish that there's a few more things to do.
Some of the classes depend on react-native (RCanvas, Utility) and some are dedicated for react-native and should be removed for android only usage (events and view managers).
So basically you need to:
1. remove files that use `Manager | Module | Event` naming 
2. change:
```diff
- class RCanvas extends ReactViewGroup
+ class RCanvas extends ViewGroup

// I guess you'll need to implement some measuring on layout or something
```
3. Cleanup `Utility`

After that you should import the `Handler` classes to use in your app.
But if you need something basic check out [PathUtil](https://github.com/ShaMan123/react-native-reanimated-canvas/blob/master/android/src/main/java/io/autodidact/reanimatedcanvas/PathUtil.java).


If you want to RP I'll help. I might find the time to work on it.
The approach would be to split the code into two libraries. One android only the other react-native bindings dependent on the first.

**Comment by ugintl** [comment]
Thank you for a detailed answer. I am not a developer, my younger brother is, but just a beginner level. He has worked on java and kotlin. I will ask him if he understands what you are saying.

Is there anything like an sdk out there which I can just import into my app?

**Comment by ShaMan123** [comment]
Maybe this?
https://bigbadaboom.github.io/androidsvg/index.html
