### ISSUE TITLE
how to draw programatically

### ISSUE THREAD

**Issue by felixkhulis** [ShaMan123/react-native-sketch-canvas#6]
hi,
can you post a short example of how to draw a line on the canvas programmatically , for example by pressing a button. 

thanks.

**Comment by ShaMan123** [comment]
Good timing.
I'm just finishing an implementation for android.
Are you well acquainted with `react-native-reanimated`?

**Comment by ShaMan123** [comment]
BTW master is WIP so it is not stable + some things won't work on ios + is breaking.
I suggest you work for the time being on branch `old_base`.
If you obtain a ref of the canvas you are able to use a variety of available methods such as `startPath`, `addPoint`, `endPath`, `addPaths`

```js
const ref = useRef();
<Canvas ref={ref} />
ref.current.addPoint(x, y)
```

[take a look](https://github.com/ShaMan123/react-native-reanimated-canvas/blob/old_base/src/SketchCanvas.js#L322)

**Comment by ShaMan123** [comment]
see the [js hooks](../tree/master/src/hooks.ts)
or the reanimated module [RACanvasModule](../tree/master/src/RACanvasModule.ts).

you can try the next version by installing `react-native-reanimated-canvas@next` - android only for now
