### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by spocky** [ShaMan123/react-native-sketch-canvas#7]
Thanks for this updated version that looks promising !

Unfortunately I can't seem to install it :
- Current git version's package.json points to an unavailable branch (#android-working-branch)
- Current yarn version's package.json points to an unavailable script (alertConfigChangeNeededScript.js)

**Comment by ShaMan123** [comment]
It's WIP. 
I'll bump config and version and comment once I do.
Notice that ios isn't yet supported for the new implementation. I'm planning to work  on it this week.

**Comment by ShaMan123** [comment]
try the next version by installing `react-native-reanimated-canvas@next` - android only for now
