### ISSUE TITLE
error: bundling failed

### ISSUE THREAD

**Issue by areebvohra** [ShaMan123/react-native-sketch-canvas#9]
![Screenshot_1577369399](https://user-images.githubusercontent.com/34376767/71478853-8808f700-2813-11ea-8107-a51ac34a5015.png)

i followed the installation setup but getting this error
i also tried the @next but didn't got any luck

**Comment by ShaMan123** [comment]
`@next` should work now with some limitations

**Comment by ShaMan123** [comment]
Does this persist?
